
name: Helm Chart Validate/Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  chart-change:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          helm:
            - 'deploy/charts/**'

  helm-chart:
    needs: chart-change
    if: ${{ needs.changes.outputs.helm == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
    - run: |
        helm lint deploy/charts/version-checker
